ТЗ 14
sanekprofit/java-shareit pull request #2
Opened 2023-07-02 02:48 UTC by sanekprofit

Я рад что этот ад закончился

2023-07-02 03:03 UTC, sanekprofit commented
Интересные тесты получаются тут, хотя локально все тесты пройдены. 
![image](https://github.com/sanekprofit/java-shareit/assets/112726168/283da9b7-be2c-43be-8a84-f49c22381260)

2023-07-02 22:19 UTC, zgreen3 requested changes
Привет. 
Проверил проект, в целом он соответствует ТЗ, это хорошо=).

Насчёт Postman-тестов: пока могу только предполагать, что правки в коде могут помочь прохождению тех 18 тестов, что падают даже локально, и того множества тестов, что падают на стороне GitHub.

Комментариев к самой работе в этот раз у меня совсем не много, потому что основные пункты ТЗ соблюдены и использование пройденных в спринте механизмов Spring и Spring Boot технически корректно. 
После принятия к сведению комментариев, присылай работу на завершение проверки.
Спасибо.

2023-07-02 22:19 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                bookings = repository.findAllByBooker_IdAndStartBeforeAndEndAfterOrderByStartDesc(userId,
Надо исправить:

Хотя в ТЗ это подробно не расписано, весьма вероятно, что для статуса "CURRENT" логика предметной области приложения подразумевает нахождение бронирований в рамках текущей даты, а не до или после неё, как получается по коду фильтров из JPA-метода репозитория в данной строке.

Т.е. нужно попробовать поменять этот метод на, например, такой:
`findAllByBooker_IdAndStartAfterAndEndBeforeOrderByStartDesc(...)`,

тогда, кроме большего соответствия предметной логике приложения есть вероятность, что ошибки в тестах Postman уйдут: я локально, кстати, вижу стабильно 18 ошибочных тестов в Postman при рестарте приложение с кодом, соответствующем данному пул-реквесту.

2023-07-02 22:19 UTC, zgreen3 commented on src/main/resources/schema.sql
> +CREATE TABLE IF NOT EXISTS users (
Отлично:

Вижу, что здесь корректно написаны DDL SQL-выражения для создания таблиц для основных сущностей проекта (причём, даже не только для Item и User, как требовалось по ТЗ), отлично!

Для информации:

Полезно иметь ввиду, что в синтаксисе PostgreSQL допустимы разные варианты указания внешнего ключа: https://stackoverflow.com/a/28560619 , на разных рабочих проектах могут встретиться все 4, какое-либо предпочтение между ними сложно определить, поэтому выбор синтаксиса обычно зависит от договорённостей внутри команды проекта (общего для команды стиля написания sql-кода).

2023-07-02 22:19 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/booking/model/Booking.java
> +    @ManyToOne
Отлично:

Вижу, что ты в целом разобрался в написании основных классов сущностей (моделей) для репозиториев данного проекта с использованием аннотаций JPA, отлично!

Если есть время поразбираться, можно поискать / погуглить информацию по теме N+1 problem и в чём плюсы и минусы написания `@ManyToOne(fetch = FetchType.LAZY) `(см., например, на англ. яз. эти и подобные источники: https://vladmihalcea.com/n-plus-1-query-problem/ , https://stackoverflow.com/questions/17431312/what-is-the-difference-between-join-and-join-fetch-when-using-jpa-and-hibernate), в теории курса она тоже объясняется (см. раздел "4. Типы выборки сущностей в JPA. Нюансы работы с БД"), при этом в данном проекте тип настройки выборки не принципиален с т.з. учебных целей и ТЗ, главное, разобраться с этим ближе к диплому и в последствии =).

2023-07-02 22:19 UTC, zgreen3 commented on src/main/resources/application.properties
> -# TODO Append connection to DB
Надо исправить:

В ТЗ подразумевалось, что здесь будут прописаны настройки для БД проекта, напримерм, PostgreSQL БД.
Надо их здесь указать.

Подсказка, они могут быть указаны примерно в таком виде (если при этом возникнут проблемы с тестами, то можно будет настройки далее закомментировать и вернуть те, что указаны у тебя для H2 БД - в оставшихся проектах курса будет указано, как совместить настройки для этих разных БД в одном файле - для разных профилей - тестирования и "промышленной" работы приложения):
```
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.url=jdbc:postgresql://localhost:5434/shareit # OR port could be as a usual PostgreSQL port, 5432, depends on PostgreSQL configuration during its install in OS.
spring.datasource.username=shareit
spring.datasource.password=shareit
```

2023-07-02 22:19 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/item/ItemRepository.java
> +    List<Item> findByNameContainingIgnoreCaseOrDescriptionContainingIgnoreCaseAndAvailableIsTrue(String textName,
Отлично:

Вижу, что в целом корректно (в соответствии со схемой БД и с описаниями в ТЗ) доработаны репозитории, а также сервисы для Item и User, отлично!

2023-07-03 14:51 UTC, sanekprofit commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                bookings = repository.findAllByBooker_IdAndStartBeforeAndEndAfterOrderByStartDesc(userId,
Сделал как ты просил
![image](https://github.com/sanekprofit/java-shareit/assets/112726168/8e7df7eb-2f37-4c83-ba19-2c908110ec59)
Но появилась другая проблема 
![image](https://github.com/sanekprofit/java-shareit/assets/112726168/10cf357c-c24e-4dbc-b73d-76a9562665d4)

2023-07-03 19:10 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                bookings = repository.findAllByBooker_IdAndStartBeforeAndEndAfterOrderByStartDesc(userId,
Надо исправить:

Понял, хорошо, (если смотреть по эндпоинтам, то количество падающих с ошибкой, как понимаю, как минимум, не увеличилось, у меня получается 3 эндпоинта локально падают), у всех похожая ошибка - что-то не соответствует тестам на статус бронирования.

Значит, следующий этап - сверяем реализацию логики бронирования с ТЗ, видим такой момент: "Добавление нового запроса на бронирование. Запрос может быть создан любым пользователем, а затем подтверждён владельцем вещи. Эндпоинт — POST /bookings. После создания запрос находится в статусе WAITING — «ожидает подтверждения»".

Т.е. нужно после создания устанавливать статус запроса на бронирование в WAITING, думаю, причина падения тестов на этот раз связана с этим. Нужно скорректировать код и запустить тесты вновь (я этот момент, к слову, на предыдущей итерации тестирования не увидел, т.к. уже привык, что его отслеживают тесты=()).

2023-07-03 19:21 UTC, zgreen3 requested changes
Важно добиться того, чтобы все тесты в проекте проходили перед следующей итерацией проверки работы ревьюером, т.к. для будущей работы на реальных проектах навык отладки работы эндпоинтов для бекэнд программиста очень нужен, и именно такой работой, может, немного занудной с виду, но критически необходимой для корректного функционирования приложения, можно этот навых развить на практике.

Если возникнут какие-либо вопросы по новым тестам, советую также обратиться за разъяснениями к наставнику и, может, даже в чат когорты, т.к. эти тесты давно отлажены (уже десятки, если не больше, работ проверены, где они все "зелёные") и ревьюеры обычно проверяют работы в части, в которой сложно написать автотесты (у меня, к слову, также формально нет возможности принять работу с падающими автотестами, за этим следит платформа Практикума).

Поэтому желаю терпения и успехов в отладке оставшихся авто-тестов и на следующей итерации жду работу для завершения проверки.

2023-07-03 19:21 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> -@Transactional
Можно лучше:

Не совсем понимаю смысл удаления транзакционности над этим классом - в своих комментариях я, насколько помню, не упоминал о необходимости этого, в т.ч. потому что транзакционность полезна в малых и средних проектах для сохранения целостности данных приложения, пока не становится узким местом производительности.

2023-07-03 19:21 UTC, zgreen3 commented on src/main/resources/schema.sql
> -    FOREIGN KEY (request_id) REFERENCES requests(id)
Можно лучше:

Хотя это прямо не противоречит ТЗ (текущего спринта), не вижу смысла в удалении внешнего ключа по отношению к запросам, requests, - также как и транзакционность на уровне сервисов, на уровне БД - внешние ключи это один из инструментов обеспечения целостности данных приложения.

2023-07-04 00:59 UTC, sanekprofit commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                bookings = repository.findAllByBooker_IdAndStartBeforeAndEndAfterOrderByStartDesc(userId,
Неее, статус WAITING у меня всегда ставится 
![image](https://github.com/sanekprofit/java-shareit/assets/112726168/aec7c1bb-aaf6-4b05-9878-58766f00cd49)

2023-07-04 01:14 UTC, sanekprofit commented
Мдаа, тесты прошли с моим старым методом `findAllByItem_Owner_IdAndStartBeforeAndEndAfterOrderByStartDesc`
И как быть теперь? Оставить мой метод?

2023-07-04 01:16 UTC, sanekprofit commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> -@Transactional
Я убрал их потому что когда увидел в логах это: 
![image](https://github.com/sanekprofit/java-shareit/assets/112726168/1057a0e1-2907-4010-aac6-dea234688922)
то подумал, что данная аннотация не нужна так как она сама создаётся в репозиториях. Если хочешь могу вернуть.

2023-07-04 01:22 UTC, sanekprofit commented on src/main/resources/schema.sql
> -    FOREIGN KEY (request_id) REFERENCES requests(id)
Убрал этот ключ для того что бы тесты проходили, потому что выскакивает вот такое:
![image](https://github.com/sanekprofit/java-shareit/assets/112726168/5ffe2b31-fd16-423e-b4d6-9e1c8c50d4f8)

2023-07-04 01:23 UTC, sanekprofit commented on src/main/resources/schema.sql
> -    FOREIGN KEY (request_id) REFERENCES requests(id)
UPD: Вернул requests и убрал NOT_NULL у request_id и всё проходит.

2023-07-04 20:14 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> -@Transactional
Теперь понял логику твоих рассуждений, спасибо. В принципе, в данном проекте можно по желанию транзакционность оставить или не добавлять, т.к. она становится нужной только когда есть операция из нескольких логических шагов, которую с т.з. бизнес логики нужно провести "атомарно", иначе будет угроза целосности данных (классический пример - это перевод банковским приложением денег с одного счёта на другой, который содержит множество шагов, но важно, чтобы они все "непрерывно" прошли, или все откатились вместе в случае ошибок к исходному состоянию счетов).

+Насчёт написанного в логах - нужно разбираться в деталях (скриншот обрезан на самом интересном месте - в следующей строке должен быть указан класс, на который Спринг ссылается, что в нём не требуется транзакционность), вероятно, это связано с private полем репозиторя в сервисе (https://stackoverflow.com/questions/4396284/does-spring-transactional-attribute-work-on-a-private-method), но нужно разбираться в деталях - это за рамками учебных целей данного проекта, насколько могу судить.

2023-07-04 20:18 UTC, zgreen3 commented on src/main/java/ru/practicum/shareit/booking/BookingServiceImpl.java
> +                bookings = repository.findAllByBooker_IdAndStartBeforeAndEndAfterOrderByStartDesc(userId,
Хорошо, что так: видимо, я этот момент проглядел в коде (искал явное присвоение этого статуса новому запросу - если он в коде выставляется обращением к отдельному эндпоинту, а не в момент обращения к эндпоинту создания запроса, то автотесты могут на это ругаться).

2023-07-04 20:24 UTC, zgreen3 commented
> 

Да, вижу, что тесты прошли. Это весьма странно. В реальном проекте пришлось бы продолжать инвестировать время в поиск первопричины (иногда попадаются вопросы, которые приходится пару недель с разных сторон исследовать, даже не одним разработчиком, в особо важных и неотложных случаях, такое бывает, хотя редко). В данном учебном проекте я готов принять проект в текущем виде (т.к. теперь тесты проходят и это возможно формально, но не только по этому, а, прежде всего, потому что остальные комментарии по проекту учтены и кроме вопроса с авто-тестами я не вижу в проекте каких-либо критических моментов или отклонения от ТЗ)).

2023-07-04 20:27 UTC, zgreen3 approved these changes
По причинам, указанным в других комментариях к коду репозитория и твоим комментариям, готов принять проект в текущем виде, считаю, что учебные цели по данному проекту достигнуты. 
Встретимся на проверке следующих проектов!

2023-07-05 16:10 UTC, merged